#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A project.wsgi.celery inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

celery -A celery_app.celery \
    --broker="${CELERY_BROKER_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}" \
    --persistent=1 --db=/app/flower_db/flower.db  --state_save_interval=5000
